import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import SideNavbar from "./sideNavbar/page";
import Login from "./login/page";
import UpperNavBar from "./UpperSideBar/page";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Article",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLogin = false;

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div
          className={`${cn(
            "grid grid-cols-[0.3fr_2fr] grid-rows-[1fr] gap-x-[6px] gap-y-[0px] overflow-hidden",
            inter.className,
            {
              "debug-screens": process.env.NODE_ENV === "development",
            }
          )}`}
        >
          {isLogin ? (
            <Login />
          ) : (
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <SideNavbar />

              <div className="grid grid-cols-[1fr] grid-rows-[0.3fr_0fr] gap-x-[px] gap-y-[1px] w-full ">
                <UpperNavBar />
                <div className="mt-14 w-full p-8 ">{children}</div>
              </div>
            </ThemeProvider>
          )}
        </div>
      </body>
    </html>
  );
}
