import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import SideNavbar from "./sideNavbar/SideNavbar";
import Login from "./login/page";
import UpperNavBar from "./UpperSideBar/page";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Article",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLogin = false;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${cn("", inter.className, {
          "debug-screens": process.env.NODE_ENV === "development",
        })} `}
      >
        <div className="flex w-full overflow-hidden">
          {isLogin ? (
            <Login />
          ) : (
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <SideNavbar />
              <div className="flex w-full flex-col-reverse  ">
                <UpperNavBar />
                <div className=" p-8 mt-14">{children}</div>
              </div>
            </ThemeProvider>
          )}
        </div>
      </body>
    </html>
  );
}
